// Using an array to store each song as an object
// In addition to obv title and lyrics, I assign a distinct id to each object (used later to target the correct lyrics-block)
const arrSongList = [
    {id: "s1", title:"1.1. Kråkevisa", lyrics:"Og mannen han gjekk seg i vedaskog,<br>hei, fara, i vedaskog.<br>Då sat der ei kråke i lunden og gol.<br><br>Ref:<br>Hei fara. Faltu riltu raltura.<br><br>Og mannen han tenkte med sjølve seg,<br>hei, fara, med sjølve seg;<br>Skal tru om den kråka vil drepa meg?<br><br>Og mannen han snudde om hesten sin,<br>hei, fara, om hesten sin,<br>så køyrde han heim att til gar‘en sin.<br><br>Å høyr, du min mann, kva eg spøre deg,<br>hei, fara, eg spøre deg;<br>Kvar vart det av ve‘en du køyrde til meg?<br><br>Eg køyrde no slett ingen ve‘ til deg,<br>hei, fara, ingen ve‘ til deg,<br>for kråka ho svor ho sku‘ drepa meg.<br><br>Å no har eg aldri høyrt større skam!<br>hei, fara, høyrt større skam!<br>Har du høyrt at ei kråke kan drepe ein mann?<br><br>Men kråka kom etter på taket og gol,<br>hei, fara, på taket og gol,<br>og mannen han opp gjennom ljoren for.<br><br>Og mannen han spente sin boge for kne,<br>hei, fara, sin boge for kne,<br>så skaut han den kråka, så ho datt ned.<br><br>Så spente han føre dei folane ti,<br>hei, fara, dei folane ti;<br>men kråka ho sprengde alle di.<br><br>Så spente han føre dei folane tolv,<br>hei, fara, dei folane tolv,<br>så køyrde han kråka på låvegolv.<br><br>Så flådde han kråka og lema ho sund,<br>hei, fara, og lema ho sund,<br>ho vog innpå seksten og tjue pund.<br><br>Av skinnet så gjorde han tolv par skor,<br>hei, fara, tolv par skor,<br>det fineste paret det gav han til mor.<br><br>Og munnen han brukte te mala korn,<br>hei, fara, te mala korn,<br>og øyro han gjorde til tutar-horn.<br><br>Og den som kje kråka kan nytta så,<br>hei, fara, kan nytta så,<br>han er ikkje verd ei kråke å få"},
    {id: "s2", title:"1.2. Nu klinger", lyrics:"Nu klinger igjennom den gamle stad, påny en studentersang,<br>og alle mann alle i rekker og rad, svinger opp under begerklang!<br>Og mens borgerne våkner i køia og hører det glade kang-kang,<br>stemmer alle mann, alle mann, alle mann, alle mann, alle mann, alle mann;<br><br>Refreng:<br>Studenter i den gamle stad, ta vare på byens ry!<br>(klapp x2)<br>Husk på at jenter, øl og dram var kjempenes meny.<br>Og faller I alle mann alle, skal det gjalle fra alle mot sky.<br>La’kke byen få ro, men la den få merke det er en studenterby!<br>Og øl og dram, og øl og dram, og øl og dram, og øl og dram.<br><br>I denne gamle staden satt så mangen en konge stor,<br>og hadde nok av øl fra fat og piker ved sitt bord.<br>De laga bøljer i gata når hjem ifra gildet de fór.<br>Og nu sitter de alle mann alle i valhall og traller til oss i kor:<br><br>Refreng:......<br><br>På Elgeseter var det liv i klosteret dag og natt!<br>Der hadde de sin kagge og der hadde de sin skatt.<br>De herjet i Nonnenes gate og rullet og tullet og datt.<br>Og nu skuer de fra himmelen og griper sin harpe fatt.<br><br>Refreng:....<br><br>(Adagio)<br>Når vi er vandret hen og staden hviler et øyeblikk,<br>(kraftig klapp x2)<br>så kommer våre sønner og tar opp den gamle skikk;<br>En lek mellom muntre butuljer, samt aldri så lit’ erotikk.<br><br>(Accelerando)<br>Også sitter vi i himmelen og stemmer i vår replikk;<br><br>Refreng:<br>(Tramp/klapp hele siste refreng)<br>Studenter i den gamle stad, ta vare på byens ry!<br>(markant klapp x2)<br>Husk på at jenter, øl og dram var kjempenes meny.<br>Og faller I alle mann alle, skal det gjalle fra alle mot sky.<br>Lakke byen få ro, men la den få merke det er en studenterby!<br>(INGEN ØL OG DRAM ETTER SISTE REFRENG! Men ofte utbrytes det i en Skål!)"},
    {id: "s3", title:"1.3. Skål kamerater", lyrics:"Skål kamerater, godt humør,<br>tidsnok kommer sorgen.<br>Full i dag og full i går, også full i morgen.<br>Datt ned fra gjerdet,<br>stein dau,<br>ompa, ompa, drikk deg i hjel.<br><i>*blblblblbl*</i><br>Hei, skål!"},
    {id: "s4", title:"1.4. Helan går", lyrics:"<i>1.4.1. Forvers alternativ 1</i><br>Av tradition står ett litet glas framför alla<br>som till randen är fyllt av nubben den kalla.<br>Men den är liten så man kan rakt inte delan<br>därför nu alla vi sjunga sången om helan.<br><br><i>1.4.2. Forvers alternativ 2</i><br>Det står snaps i et litet glas framför alla<br>som er fyllt helt upp til randen med kalla.<br>Är du redd för at trilla gjenom så delan<br>men först ska vi sjunga sången om helan.<br><br><i>1.4.3. Refreng</i><br>Helan går<br>sjung hoppfaderallanlallanlej,<br>helan går<br>sjung hoppfaderallanlej.<br>Och den som inte helan tar,<br>han heller inte halvan får.<br>Helan går<br>sjung hoppfaderallanlej!"},
    {id: "s5", title:"1.5. Lambo", lyrics:"<i>Tilskuere synger:</i><br>Se der står en fyllehund, mine herrer lambo.<br>Sett nu flasken for din munn, mine herrer lambo.<br>Se hvordan den dråpen vanker ned ad halsen på den dranker<br>Lambo, lambo, mine herrer lambo<br><br><i>(Repeteres til vedkommende verset er rettet mot har drukket opp.)<br><br>Dranker synger:</i><br>Jeg mitt glass utdrukket har, mine herrer lambo.<br>Se der fins ei dråpen kvar, mine herrer lambo.<br>Som bevis der på jeg vender, flasken på dens annen ende<br><i>(Drankeren vender fysisk glass/flaske el. annet med toppen ned over hodet som bevis.)<br><br>Tilskuere synger:</i><br>Lambo, lambo, mine herrer lambo<br>Hun/han kunne kunsten hun/han var et jævla fyllesvin.<br>Så går vi til nestemann og ser hva hun/han formår.<br><br><i>(Finn en ny person og fortsett til man går lei, eller folk er tomme for drikke.)</i>"},
    {id: "s6", title:"1.6. Du skal få en dag i mårå", lyrics:"Du skal få en dag i mårå som itte blir så bra,<br>med skallebank og kuppel - helt solid<br>Med det kan du rette oppat hvis du passer på å ha<br>en flaske pils og så en paracett.<br><br>Og hvis det itte hjelper deg så får du tenke att -<br>je lyt da ofre noe for all moroa i natt.<br><br>Du skal få en dag i mårå som itte blir så bra,<br>men hold deg pigg til du går herifra."},
    {id: "s7", title:"1.7. Himmelseng", lyrics:"<i>Første vers</i><br>Jeg ønsker meg en himmelseng<br>en himmelseng med speil i<br>slik at jeg kan speile meg<br>og se hvor jeg er deilig<br><br><i>Refreng</i><br>Hey lå li lå li lå<br>li lå li lå li låa,<br>hey lå li lå li lå<br>li lå li lå li låa!<br>Ompa ompa ompa sprut,<br>ompa ompa sprut sprut!<br><br><i>Div. vers</i><br>Jeg møtte på en homofil<br>han ville ta meg bakfra<br>men jeg tok å lurte han<br>jeg snudde meg og gapa<br><br>Jeg møtte på en lommemann<br>han hadde no’ i lomma<br>det var ikke sukkertøy<br>jeg klemte til, det skumma<br><br>Jessmann han var tjue år<br>Linda hun var tretten<br>det brydde ikke han seg om<br>nå må han stå i retten<br><br><i>Avsluttende vers</i><br>Jeg trenger ingen himmelseng<br>en himmelseng med speil i<br>jeg trenger ikke speile meg<br>jeg vet hvor jeg er deilig"},
    {id: "s8", title:"1.8. Det er det samme hvor jeg havner når jeg dør", lyrics:"Det er det samme hvor jeg havner når jeg dør,<br>det er det samme hvor jeg havner når jeg dør,<br>for jeg har venner begge steder<br>som vil motta meg med heder,<br>det er det samme hvor jeg havner når jeg dør<br><br>Vil du elske alle piker før du dør,<br>vil du elske alle piker før du dør,<br>må du finne, notabene,<br>litt av alle hos den ene,<br>hvis du vil elske alle piker før du dør.<br><br>D’ække sikkert vi får brennvin når vi dør,<br>d’ække sikkert vi får brennvin når vi dør,<br>så la oss derfor drikke drammen,<br>nu i aften, vi er sammen,<br>d’ække sikkert vi får brennvin når vi dør.<br><br>Minst en kjeller må man lukke når Brage dør,<br>minst en kjeller må man lukke når Brage dør,<br>for han har alt sitt på det tørre,<br>intet forbruk har vært større,<br>minst en kjeller må man lukke når Brage dør.<br><br>Det blir ingen prestetale når jeg dør,<br>det blir ingen prestetalen når jeg dør,<br>jeg skal minnes ved et beger<br>som en gammel skjørtejeger,<br>det blir ingen prestetale når jeg dør.<br><br>Du skal få min gamle sykkel når jeg dør,<br>du skal få min gamle sykkel når jeg dør,<br>for de siste kilometer,<br>tar jeg tandem med St. Peter ,<br>du skal få min gamle sykkel når jeg dør.<br><br>Jeg skal spille med St.Peter når jeg dør,<br>jeg skal spille med St.Peter når jeg dør,<br>står jeg på som jeg pleier,<br>kan jeg loppen for en bayer,<br>jeg skal spille med St.Peter når jeg dør."},
    {id: "s9", title:"1.9. Full i dag", lyrics:'Full i dag<br>og full i morgen<br>slik har livet blitt for meg,<br>jeg skal aldri svikte flaska,<br>jeg skal aldri gifte meg.<br><br>På min gravstein<br>på min gravstein,<br>skal det skrives på latin:<br>"Under denne lille gravsten<br>ligger et jævla fyllesvin."'},
    {id: "s10", title:"1.10. Vi äro små humlor", lyrics:"Vi äro små humlor vi, bzz, bzz.<br>Vi äro små humlor vi, bzz, bzz.<br>Vi äro små humlor som tar oss en geting.<br>Vi äro små humlor vi, bzz, bzz.<br><br>Vi äro små fiskar vi, blupp, blupp.<br>Vi äro små fiskar vi, blupp, blupp.<br>Vi äro små fiskar som fått oss en kallsup.<br>Vi äro små fiskar vi, blupp, blupp.<br><br>Vi äro små änglar vi, flaks-flaks.<br>Vi äro små änglar vi, flaks-flaks.<br>Vi äro små änglar som tar oss en djävel.<br>Vi äro små änglar vi, flaks-flaks."},
    {id: "s11", title:"1.11. Bært-bært visa", lyrics:"Har du hørt om hu Titten-Tulla<br>Det va hu jeg fikk mitt aller første (bært bært)<br>Hjelp meg med å rime her, for jeg kan ikke noe om det der<br><br>Erna hu kalte meg for smukken<br>Det va ho jeg smelte første gang på (bært bært)<br>Hjelp meg med å rime her, for jeg kan ikke noe om det der<br><br>Når hu Lisbeth er i sjulet<br>Da gjør hu ikke annet enn å (bært bært)<br>Hjelp meg med å rime her, for jeg kan ikke noe om det der<br><br>Når hu May-Britt står på trikken<br>Da får hu alltid lyst til å slikke (bært bært)<br>Hjelp meg med å rime her, for jeg kan ikke noe om det der<br><br>I klosteret er det munker<br>De slukker alltid lyset når de (bært bært)<br>Hjelp meg med å rime her, for jeg kan ikke noe om det der<br><br>Tralli lalli lalla lalla"},
    {id: "s12", title:"1.12. Kråketur", lyrics:"<i>Melodi: Mummi</i><br>Du store min som tiden flyr,<br>Nå er vi her på nye eventyr<br>Med kråkefar og alle vennene<br>Ja dette blir nok spennende!<br>Her kommer kråka, Her kommer kråka<br><br>Med dressjakke og shortsen på<br>En øl i hånd skal alle få<br>Med promille høy er vi på topp<br>Vi drikker til det sier stopp!<br>Ja det er kråka, ja det er kråka, ja det er kråka<br><br>Kra kra kra kra kra kra kra kra kra, kra kra kra<br>kra kra kra kra kra kra,"},
    {id: "s13", title:"1.13. Drunken sailor", lyrics:"What do you do with a drunken sailor,<br>What do you do with a drunken sailor,<br>What do you do with a drunken sailor,<br>Earl-eye in the morning!<br><br>Refreng:<br>Weigh heigh and up she rises<br>Weigh heigh up she rises<br>Weigh heigh up she rises<br>Earl-eye in the morning<br><br>Shave his belly with a rusty razor,<br>Shave his belly with a rusty razor,<br>Shave his belly with a rusty razor,<br>Earl-eye in the morning!<br><br>Ref.<br><br>Put him in the hold with the Captain’s daughter,<br>Put him in the hold with the Captain’s daughter,<br>Put him in the hold with the Captain’s daughter,<br>Earl-eye in the morning!<br><br>Ref.<br><br>Put him the back of the paddy wagon,<br>Put him the back of the paddy wagon,<br>Put him the back of the paddy wagon,<br>Earl-eye in the morning!<br><br>Ref<br><br>Throw him in the lock-up ’til he’s sober,<br>Throw him in the lock-up ’til he’s sober,<br>Throw him in the lock-up ’til he’s sober,<br>Earl-eye in the morning!<br><br>Ref.<br><br>Throw him in a room full of bagpipe music,<br>Throw him in a room full of bagpipe music,<br>Throw him in a room full of bagpipe music,<br>Earl-eye in the morning!<br><br>Ref.<br><br>That’s what we do with a drunken sailor,<br>That’s what we do with a drunken sailor,<br>That’s what we do with a drunken sailor,<br>Earl-eye in the morning!"},
    {id: "s14", title:"1.14. Artillerisangen", lyrics:"Hva skal vi gjøre med kanonene da?<br>Hva skal vi gjøre med dem, hva skal vi gjøre med dem..<br>Jo dem skal vi skyte, jo dem skal vi skyte,<br>jo dem skal vi skyte små spurvene med.<br><br>Og hva skal vi gjøre med små spurvene da?<br>Hva skal vi gjøre med dem, hva skal vi gjøre med dem..<br>Jo dem skal vi ribbe, jo dem skal vi ribbe,<br>jo dem skal vi ribbe små fjærene av.<br><br>Og hva skal vi gjøre med små fjærene da?<br>Hva skal vi gjøre med dem, hva skal vi gjøre med dem..<br>Jo dem skal vi stappe, jo dem skal vi stappe,<br>jo dem skal vi stappe madrassene med.<br><br>Og hva skal vi gjøre med madrassene da?<br>Hva skal vi gjøre med dem, hva skal vi gjøre med dem..<br>Jo dem skal vi legge, jo dem skal vi legge,<br>jo dem skal vi legge små pikene på.<br><br>Og hva skal vi gjøre med små pikene da?<br>Hva skal vi gjøre med dem, hva skal vi gjøre med dem..<br>Jo dem skal vi lage, jo dem skal vi lage,<br>jo dem skal vi lage små guttene med.<br><br>Og hva skal vi gjøre med små guttene da?<br>Hva skal vi gjøre med dem, hva skal vi gjøre med dem..<br>Jo dem skal vi lære, jo dem skal vi lære,<br>jo dem skal vi lære å SKYTE MED KANON!"},
    {id: "s15", title:"1.15. Theodor", lyrics:"Jeg elskede sjøen ifra jeg var ung<br>og svømmede om som en sei<br>faderiorei!<br><br>En dag da jeg badet min velskapte kropp<br>kun bagenden ragede opp<br>faderiorei!<br><br>Folk ropte: “Der svømmer en aligator!”<br>Så var det (klapp klapp) til Theodor<br>Folk ropte: “Der svømmer en aligator!”<br>Så var det (klapp klapp) til Theodor"},
    {id: "s16", title:"1.16. The Wild Rover", lyrics:"I’ve been a wild rover for many a year<br>And I spent all my money on whiskey and beer,<br>And now I’m returning with gold in great store<br>And I never will play the wild rover no more.<br><br>Refreng:<br>And it’s no, nay, never,<br><i>(4xClap / right up yer kilt!)</i><br>No nay never no more,<br><i>(2xClap / Harp harp!)</i><br>Will I play the wild rover<br><i>(1xClap / Guinness!)</i><br>No never no more.<br><br>I went to an ale-house I used to frequent<br>And I told the landlady my money was spent.<br>I asked her for credit, she answered me ”nay<br>Such a custom as yours I could have any day.”<br><br>Ref.<br>I took from my pocket ten sovereigns bright<br>And the landlady’s eyes opened wide with delight.<br>She said ”I have whiskey and wines of the best<br>And the words that I spoke sure were only in jest.”<br><br>Ref.<br>I’ll go home to my parents, confess what I’ve done<br>And I’ll ask them to pardon their prodigal son.<br>And if they caress me as ofttimes before<br>Sure I never will play the wild rover no more."},
    {id: "s17", title:"1.17. Kongesangen/hyllest til øl", lyrics:"<i>Melodi: God Save the Queen</i><br>Gud sign vår konge god!<br>sign ham med kraft og mot<br>sign hjem og slott!<br>Lys for ham ved din Ånd,<br>knytt med din sterke hånd<br>hellige troskapsbånd<br>om folk og drott!<br><br>Høyt sverger Norges mann<br>hver i sitt kall, sin stand<br>troskap sin drott.<br>Trofast i liv og død,<br>tapper i krig og nød,<br>alltid vårt Norge lød<br>Gud og sin drott<br><br>Øl er vårt levebrød<br>bedre enn korn og frø<br>for øl kan jeg dø!<br><i>DRIKK ØL!</i><br>Denne var kjempe god<br>nå fikk min sjel litt ro<br>øl er min beste venn<br>vi skåler igjen!"},
    {id: "s18", title:"1.18. Norges Skaal", lyrics:"For Norge, Kjempers Fødeland,<br>Vi denne Skål vil tømme,<br>Og når vi først får Blod på Tann,<br>Vi søtt om Frihet drømme;<br>Dog våkner vi vel opp engang<br>Og bryter Lenker, Bånd og Tvang;<br>For Norge, Kjempers Fødeland,<br>Vi denne Skål vil tømme!<br><br>Hver tapper Helt, blandt Klipper født,<br>Vi drikke vil til Ære;<br>Hver ærlig Norsk, som Lenker brøt,<br>Skal evig elsket være!<br>Den vrede Livvakts Våbenbrak<br>Forklarer trolig Nordmenns Sak.<br>Hver ærlig Norsk, blandt Klipper født,<br>Vi drikker nå til Ære!<br><br>En Skål for Deg, min kjekke Venn,<br>Og for de norske Piker!<br>Og har Du en, så Skål for den!<br>Og Skam for den, som sviker!<br>Og Skam for den, som elsker Tvang<br>Og hater Piker, Vin og Sang!<br>En Skål for Dig min kjekke Venn,<br>Og for de norske Piger!<br><br>Og nok en Skål for Norges Fjell,<br>For Klipper, Snø og Bakker!<br>Hør Dovres Ekko rope: «Hell!»<br>Før Skålen tre Gang takker.<br>Ja tre Gang tre skal alle Fjell<br>For Norges Sønner roper Hell;<br>Ennå en Skål for Deg mitt Fjell,<br>For Klipper, Snø og Bakker"},
    {id: "s19", title:"1.19. Jeg er en liten kråke", lyrics:"<i>Melodi:Jeg er en papegøye fra Amerika</i><br><br>Jeg er en liten kråke i fra kjellern kra,<br>Der blir jeg full og er det hele tiden.<br><br>Jeg drikker mest av alle, mine venner sa:<br>det gjør at han blir veldig, veldig sliten<br><br>og det blir jeg og falleri og fallera,<br>hvis noen spør meg hvor jeg kommer fra<br><br>jeg svarer falleri og fallera,<br>jeg er en jævla kråke i fra kjellern kra<br>SKÅL!"},
    {id: "s20", title:"1.20. Theobald-Thor", lyrics:"En mann som hette Theobald-Tor<br>han var en skikk’lig tamburmajor<br>Suksessen han gjorde var alltid stor<br>når han snurret og svingte sin kuk<br><br>Ref:<br>Det var en stor kuk<br>lang, kraftig og tung!<br>Fra dens topp til dens rot<br>var den tre-fire fot<br>med en middelstor ryggsekk til<br>pung, pung, pung, pungelipung,<br>pung, pung, pung<br><br>En dag gikk Theobald ut en stund<br>og gikk for seg selv i en liten lund.<br>Han møtte en søt, liten dame med hund<br>som så ham svinge sin kuk<br>REF<br><br>Og Teobald prøvde et triks han hadd’ lært<br>og slapp sitt lem med et kraftig snert<br>i hodet på hunden som omkom tvert<br>mens han snurret og svingte sin kuk<br>REF<br><br>Men damen hun ble helt forrykt<br>og bannet og skrek aldeles stygt<br>så det ble ingen lykk’lig flørt<br>for mannen som svingte sin kuk<br>REF<br><br>På grunn av damens kjeftesmell<br>han allerede samme kveld<br>ble sittende i en ensom cell’<br>der han snurret og svingte sin kuk<br>REF<br><br>Når saken kom i retten opp<br>sa aktor’n det får være stopp<br>man får ikke vifte med sin snopp<br>å snurre og svinge sin kuk<br>REF<br><br>Men dommern han var tolerant<br>han sa selv gjør jeg likedan<br>jeg synes det er interessant<br>å snurre og svinge min kuk<br>REF<br><br>Så Theobald han slipptes fri<br>og likt som dommeren synes vi<br>at folk og fe skal drite i<br>om vi snurrer og svinger vår kuk<br><br>For jeg har en stor kuk,<br>lang, kraftig og tung!<br>Fra dens topp til dens rot er den SJUÅTTE FOT<br>med en KJEMPESTOR ryggsekk til pung,<br>pung, pung, pungelipung, pung, pung, pung<br>pungelipung! Pungelipung!"},
    {id: "s21", title:"1.21. Kråkeymnen", lyrics:"<i>Melodi: Bruspulverguttene</i><br><br>For vi gjør slettes ingenting vi bare flakser rundt<br>omkring og drikker øl<br>(klirring i klass)*2 KRA KRA!<br>For du skal se når vi flyr på tur<br>Da vil du høre en kråkelur<br>Det er på kjellern vi hører til<br>Der blir det nå alltid krøll<br>Der drikker vi masse øl!!!<br>For vi er Kråker fra kråkelurn<br>Du ser oss bånne nedpå hver vår store øl<br>FOR VI ER KRÅKER FRA KRÅKELURN<br>SOM DRIKKER ØL<br>(klirring i klass)*2 KRA KRA!<br>KRRRRRAKRAKRARKRAKRAKRAKRA.......<br><br>Å, du skal høre vi stemmer i<br>Det likner en symfoni<br>Men i kjellern vi synger i<br>Fins ingen som hører; vi<br>Tar rotta på Mercury<br>Men det gir vi flatt faen i<br>Så vi bælmer nedpå nok en billig øl<br>FOR VI ER NU SMÅ FISKAR VI<br>SOM DRIKKER ØL<br>(klirring i klass)*2 BLUBB BLUBB!<br>KRRRRRAKRAKRARKRAKRAKRAKRA......."},
    {id: "s22", title:"1.22. Vi lister oss", lyrics:"Vi lister oss så stilt vi må<br>når vi skal ut på kjøret<br>Vi drikker bare det vi må,<br>litt mer en vi behøver<br>Vi drikker altså alt vi kan<br>fra øl og sprit til gurglevann<br>og ellers så spyr vi så lite vi kan;<br>Selvom det ender med kræsj og bang!"},
    {id: "s23", title:"1.23. God Jul", lyrics:"God Jul x3<br><br>En favn med ved – En favn med ved<br>En mann med skjegg – En mann med skjegg<br>Ribbekjøtt, pinnekjøtt, torsk og rypestegg<br><br>Lufta full av snø – Lufta full av snø<br>En liten Jesus her – En liten Jesus her<br>Julegran, marsipan, presanger og røde klær<br><br>God Jul x3<br><br>En kjeft med gløgg – En kjeft med gløgg<br>Et fuglenek – Et fuglenek<br>Julesalg, juletalg, frost og utelek<br><br>Drikke akevitt – Drikke akevitt<br>Gå rundt et tre – Gå rundt et tre<br>Rosenkål, nøtteskål, ro og julefred<br><br>God Jul x3"},
    {id: "s24", title:"1.24. Øl, øl og mere øl", lyrics:"Ref.<br>Øl, øl og mere øl<br>Det e det skjønnaste eg vet<br>Øl, øl og mere øl<br>Det e å bli min store kjærlighet<br>Ja, noen elsker kaffe<br>Og snaps av fingerbøl<br>Men spar meg for andre laster<br>Enn øl, øl, øl<br><br>Eg satt på stranden med ei lita tutta<br>Ei sommarnatt ved middelhavets kyst<br>Hu beit meg litt i øyra og så sa hu. (Hva sa hu)<br>Kjære gulle mitt, no må du gjer som du har lyst<br><br>Ref.<br><br>Eg glede meg gal til juleaften<br>Eg telle daga heilt frå første mai<br>Eg skjelve når eg pakke opp presangar<br>Det e ei deilig stund, for eg veit jo ka som e på vei<br><br>Ref.<br><br>La, la, la, la, la, la, la, la, la, la, hei!<br>La, la, la, la, la, la, la, la, la, la, hei!<br>La, la, la, la, la, la, la, la, la, la, åååååååååå!<br><br>Ref. 2x"},
    {id: "s25", title:"1.25. Barley Mow", lyrics:"Here’s good luck to the pint pot<br>good luck to the barley mow (rop ut GOOD LUCK og ta en slurk!)<br>jolly good luck to the pint pot<br>good luck to the barley mow<br>oh the pint pot, half a pint<br>gill pot, half a gill, quarter gill<br>nippikin and the brown bowl<br>here’s good luck (GOOD LUCK! Slurk er valgfritt)<br>good luck to the barley mow<br>mow mow mow mow mow mow mow mow<br><br>here’s good luck to the<br>quart pot, good luck to the barley mow etc.<br>half gallon<br>gallon<br>half barrell<br>barrell<br>landlord<br>landlady<br>daughter<br>dreyer<br>slavey<br>bookie<br>brewer<br>company"}
];

// Fetch the invisible div I want the songs to be in
const divSongList = document.getElementById("divSongList");

for (let i=0; i<arrSongList.length; i++) {
    // Iterate through the list and create a new div block per song
    let addSong = document.createElement("div");
    addSong.id = arrSongList[i].id;
    addSong.className = "songBox";
    addSong.innerHTML = "<h2><i>"+arrSongList[i].title+"</i></h2>";

    // The lyrics are added as an initially invisible paragraph within each song-div
    let addLyrics = document.createElement("div");
    addLyrics.innerHTML = arrSongList[i].lyrics;
    addLyrics.style.display = "none";
    // With their own id, which I'll fetch later
    addLyrics.id = arrSongList[i].id+"_lyr";
    addLyrics.className = "lyricBox" // For styling

    addSong.append(addLyrics);
    divSongList.appendChild(addSong);
}

// Another array for the songBox div's themselves, which I'll need to...
const arrSongBox = document.getElementsByClassName("songBox");

// Need a function to make each songBox its own "button" to toggle its lyrics
function attachToggle(index) {
    arrSongBox[index].addEventListener("click", function(){
        // This will then find that corresponding lyric-paragraph (via the new array's index)
        let lyricPara = document.getElementById(arrSongBox[index].id+"_lyr");
        // and simply toggle the CSS display
        if (lyricPara.style.display === "none") {
            lyricPara.style.display = "block";
        }
        else {
            lyricPara.style.display = "none";
        }
    });
}

// Then we simply iterate this through all the songs
for (let i=0; i<arrSongBox.length; i++) {
    attachToggle(i);
}